[package]
name = "raytracer"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
glam = { version = "0.30", features = ["fast-math"] }
png = "0.17"
rand = "0.9"
rayon = "1"

[dependencies]
glam.workspace = true
png.workspace = true
rand.workspace = true
rayon.workspace = true
